### ISSUE TITLE
Port to React Issues with light position

### ISSUE THREAD

**Issue by nhtoby311** [Ameobea/three-good-godrays#8]
So I'm trying to port this effects to React, and encounter couple of issues:

- The light position of God Rays effects seems to be inversed, where the light should actually be. 
- The volumetric fog seems too large, wonder if it working correct with the `shadow-map` value.
- The color seems to be off after apply this Effects. Apply other `react-postprocessing` doesn't result in this much de-saturation. 

I have create a codesandbox for this issue: https://codesandbox.io/p/devbox/godrays-wshcfk?file=%2Fsrc%2FScene.tsx%3A33%2C9-33%2C22

![image](https://github.com/Ameobea/three-good-godrays/assets/52330522/26b5720d-d6a1-491e-8a4e-43c965080513)

**Comment by Ameobea** [comment]
Hey, thanks for trying out the library.

For the first two issues regarding the positioning and size of the effect, I've forked your codesandbox and added in some helpers that are built-in to Three.JS to help visualize the directional light and its camera's view frustum:

[Codesandbox fork](https://codesandbox.io/p/devbox/godrays-forked-z83zlp?file=%2Fsrc%2FScene.tsx%3A19%2C11&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clroff0zq00082v6n3c73tzxo%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clroff0zq00032v6noerge31y%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clroff0zq00052v6n309qgx1v%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clroff0zq00072v6nyz9v6xrd%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clroff0zq00032v6noerge31y%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clroff0zq00022v6nm278fr3w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A19%252C%2522startColumn%2522%253A11%252C%2522endLineNumber%2522%253A19%252C%2522endColumn%2522%253A11%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FScene.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clroff0zq00032v6noerge31y%2522%252C%2522activeTabId%2522%253A%2522clroff0zq00022v6nm278fr3w%2522%257D%252C%2522clroff0zq00072v6nyz9v6xrd%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clroff0zq00062v6na73sdy88%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clroff0zq00072v6nyz9v6xrd%2522%252C%2522activeTabId%2522%253A%2522clroff0zq00062v6na73sdy88%2522%257D%252C%2522clroff0zq00052v6n309qgx1v%2522%253A%257B%2522id%2522%253A%2522clroff0zq00052v6n309qgx1v%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clroff0zq00042v6nir0j9f3u%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clroff0zq00042v6nir0j9f3u%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

I also added the `shadows` prop to your `Canvas` which is required to enable shadows.

Also, you need to add `castShadow` and `receiveShadow` props to the top-level `<mesh>` components in order to get shadows working properly.  I updated the code to fix these things, and now the godrays effect is applying properly:

![](https://i.ameo.link/btk.png)

As for de-saturation or other coloration issues, I tracked down the cause of that.

The pmndrs postprocessing library expects its buffers to store colors in sRGB format, but I was storing them as linear.  I pushed a new version of `three-good-godrays` (0.6.0-rc1) that defaults that to sRGB, and the colors now look correct.

So, you'll have to update your `package.json` to have `"three-good-godrays": "0.6.0-rc1"`.

I'll be publishing version 0.6.0 shortly after I update docs.  Thanks for bringing this to my attention.

After making all those changes, I believe everything is working as expected:

![](https://i.ameo.link/btm.png)

Here's another link to my forked codesandbox with all the changes I made: [forked codesandbox](https://codesandbox.io/p/devbox/godrays-forked-z83zlp?file=%2Fsrc%2FScene.tsx%3A22%2C5&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clroff0zq00082v6n3c73tzxo%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clroff0zq00032v6noerge31y%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clroff0zq00052v6n309qgx1v%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clroff0zq00072v6nyz9v6xrd%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clroff0zq00032v6noerge31y%2522%253A%257B%2522id%2522%253A%2522clroff0zq00032v6noerge31y%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clroff0zq00072v6nyz9v6xrd%2522%253A%257B%2522id%2522%253A%2522clroff0zq00072v6nyz9v6xrd%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clroff0zq00062v6na73sdy88%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clroff0zq00062v6na73sdy88%2522%257D%252C%2522clroff0zq00052v6n309qgx1v%2522%253A%257B%2522id%2522%253A%2522clroff0zq00052v6n309qgx1v%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clroff0zq00042v6nir0j9f3u%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clroia3ej00292v74chbgiwxd%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clroia3ho002qedj40j55fduf%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clroff0zq00042v6nir0j9f3u%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

I hope this helps make the project useful for what you want to do with it!

**Comment by nhtoby311** [comment]
Thank you so much, It looks amazing now!

Probably due to without helper visualization, and the shadow casting, I was confused about the position of the light. Sorry about that! Really appreciate the codesandbox!

A bit of side question, I want to decrease the size of the light, and I do that by adjusting `shadow-camera`'s top, left, right, bottom, however, this produce this weird artifact line to the plane. I wonder if this is avoidable or this is limitation of `DirectionalLight`?
![image](https://github.com/Ameobea/three-good-godrays/assets/52330522/db3457a0-8b4b-4c58-95f4-4b54a3df2750)

**Comment by Ameobea** [comment]
Those artifacts are called "shadow acne".  They're a side effect of the way the shadow mapping is implemented internally in Three.JS.

I think the problem is especially bad here since it's on a plane which is infinitely thin, and shadows read out of the depth buffer.  I'd suggest swapping the plane out for a box geometry or similar.  You can also tweak the shadow camera's `bias` property which is designed to help with this situation as well.

**Comment by nhtoby311** [comment]
Thank you for the explanation!

I also have one more question related to light position. Is it possible to animate the volumetric light along with the light position? Right now if I update the light position, it only update the light and shadow, not the volumetric part. You can check it this codesandbox: https://codesandbox.io/p/devbox/godrays-forked-h97mwk?file=%2Fsrc%2FScene.tsx%3A31%2C77

![image](https://github.com/Ameobea/three-good-godrays/assets/52330522/b6f9d743-f4a9-4979-bf30-2403d05db529)

**Comment by Ameobea** [comment]
Hi,

It was previously required to call `.setParams` on the godrays pass whenever the light was updated.

I've pushed a new version of `three-good-godrays` that will now do this automatically.  Please update to version 0.6.1 of the library and it should work.

**Comment by nhtoby311** [comment]
Thank you! It works perfectly now! Amazing library!
